export const GET_RECIPE_PENDING = "GET_RECIPE_PENDING";
export const GET_RECIPE_RECIVED = "GET_RECIPE_RECIVED";
export const GET_RECIPE_NOTFOUND = "GET_RECIPE_NOTFOUND";

export const POST_RECIPE_PENDING = "POST_RECIPE_PENDING";
export const POST_RECIPE_RECIVED = "POST_RECIPE_RECIVED";
export const POST_RECIPE_NOTFOUND = "POST_RECIPE_NOTFOUND";

export const DELETE_RECIPE_PENDING = "DELETE_RECIPE_PENDING";
export const DELETE_RECIPE_RECIVED = "DELETE_RECIPE_RECIVED";
export const DELETE_RECIPE_NOTFOUND = "DELETE_RECIPE_NOTFOUND";

export const UPDATE_RECIPE_PENDING = "UPDATE_RECIPE_PENDING";
export const UPDATE_RECIPE_RECIVED = "UPDATE_RECIPE_RECIVED";
export const UPDATE_RECIPE_NOTFOUND = "UPDATE_RECIPE_NOTFOUND";
